version: 0.2

phases:
  install:
    commands:
    #install node 12
    - echo installing node 12
    - curl -sL https://deb.nodesource.com/setup_12.x |  bash -
    - apt install nodejs
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i
  build:
    commands:
      - echo building
      - ng build
artifects:
  files:
    - "**/*"
  base-directory: dist