version: 0.2

phases:
  install:
    commands:
    #install node 12
    - echo installing node 12
    - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    - sudo apt install nodejs
  pre_build:
    commands:
      - echo installing dependencies...
      - sudo npm i
  build:
    commands:
      - echo building
      - sudo ng build
artifects:
  files:
    - "**/*"
  base-directory: dist